# Generated by Django 3.1.3 on 2020-11-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(default='default-title-img.png', upload_to='images/'),
        ),
    ]
