# Generated by Django 3.1.3 on 2020-12-20 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0002_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='entry_favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='blog_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
